### ISSUE TITLE
Stuck at “Dumping Data into Database”

### ISSUE THREAD

**Issue by mgavinster** [gaiaehr/gaiaehr#53]
Hi there, 

Please assist as i can’t seem to get past this stage: “Dumping Data into Database” it been stuck at this stage for hours now.

Please can someone give me some guidance. 

Thank in advance
Michelle

**Comment by hrivera787** [comment]
Hi Michelle;

This occur because, the SQL dump, have the entire RxNorm data inside the
initial configuration of GaiaEHR.
We have to separate this data into another thread.

MySQL has a timeout for every statement execution and this is causing the
problem.

Later I will post a fix for this.

On Wed, Mar 2, 2016 at 7:20 AM, mgavinster <notifications@github.com> wrote:

> Hi there,
>
> Please assist as i can’t seem to get past this stage: “Dumping Data into
> Database” it been stuck at this stage for hours now.
>
> Please can someone give me some guidance.
>
> Thank in advance
> Michelle
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gaiaehr/gaiaehr/issues/53>.
>



-- 
*Héctor Rivera Falú*

*Senior **Developer* *| The Right Answer, Inc.*
787.275.5120 (w)
hrivera@tranextgen.com


The information contained in this transmission is privileged and
confidential. It is only for use by the intended recipient. If the reader
of this message is not the intended recipient, you are hereby notified that
any dissemination, distribution, or copy of this E-mail is strictly
prohibited. If you received this E-mail in error please notify the sender
promptly by reply E-Mail, then delete this E-Mail, and destroy any copies.

**Comment by mgavinster** [comment]
Thank you so much for the quick response. Would you mind letting me know once you have uploaded / posted the changes and what changes you have uploaded.

 

Thanks in advanced.

 

Kind regards

Michelle

**Comment by gopmarko** [comment]
Where can I find config scripts to compile this?

**Comment by vela1606** [comment]
Project moved to [mdtimeline](https://github.com/mdtimeline/mdtimeline)
